---
- name: Provision EC2 instance
  hosts: localhost
  gather_facts: False
  vars_files:
    - /root/ansible_projects/ansible_project_ansible_inventory/ec2_secret.yml

  tasks:
    # Tasks go here
    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        name: "gitlab"
        region: eu-central-1
        instance_type: t2.small
        image_id: ami-024f768332f080c5e
        key_name: gitlab
        security_group: sg-0751bec03b38f3bf7
        state: running
      register: ec2_instance

    - name: debug
      debug: 
        var: ec2_instance

    - name: Add new instance to in-memory inventory
      add_host:
        name: "{{ item.public_ip_address }}"
        groups: "ec2_instances"
      loop: "{{ ec2_instance.instances }}"

# - name: Run a command on the EC2 instance
#   hosts: ec2_instances
#   gather_facts: no
#   vars:
#     ansible_ssh_private_key_file: /root/.ssh/gitlab.pem
#     ansible_user: ec2-user
#   tasks:
#     - name: Run an arbitrary command
#       ansible.builtin.shell: |
#         curl -L --output cloudflared.rpm https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-x86_64.rpm
#         sudo yum localinstall -y cloudflared.rpm
#         sudo cloudflared service install eyJhIjoiNGU4Y2QzZmExMDFhOGZlMzFlOGJlODYzZDkyNjM4ZDEiLCJ0IjoiYWY3OGM4YjUtMWRlOS00ZGJkLWE5OWEtNDVkMzU3ZTVlY2YxIiwicyI6IlltVXhZalF4WWpZdE9UZ3pNaTAwTkRReExUa3pNemN0T1RobE1qSXpNV1U1TlRJeiJ9
#         sudo hostnamectl set-hostname gitlab.superlab.win
#         sudo dnf install -y policycoreutils-python-utils openssh-server openssh-clients perl
#         sudo systemctl enable sshd
#         sudo systemctl start sshd
#         sudo firewall-cmd --permanent --add-service=http
#         sudo firewall-cmd --permanent --add-service=https
#         sudo systemctl reload firewalld
#         curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.rpm.sh | sudo bash
#         sudo EXTERNAL_URL="https://gitlab.superlab.win" dnf install -y gitlab-ee

