---
- name: Provision EC2 instance
  hosts: localhost
  gather_facts: False
  vars_files:
    - /root/ansible_projects/ansible_project_ansible_inventory/ec2_secret.yml

  tasks:
    # Tasks go here
    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        name: "gitlab"
        region: eu-central-1
        instance_type: t2.small
        image_id: ami-0aacb108f8342c7d5
        key_name: gitlab
        security_group: sg-0751bec03b38f3bf7
        # state: absent
      register: ec2_instance

    - name: debug
      debug: 
        var: ec2_instance